apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: eks-03-mturansk-test
  namespace: eks-03-mturansk-test
spec:
  region: us-east-2
  sshKeyName: ""
  version: v1.28
  baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
  vpc:
    availabilityZoneUsageLimit: 2
    availabilityZoneSelection: Ordered
  logging:
    enable: false
  associateOIDCProvider: true
  eksClusterName: eks-03-mturansk-test
