apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gitops-integration-policy
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-managedclustersetbinding
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: global
                  namespace: openshift-gitops
                spec:
                  clusterSet: global
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-placement
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Placement
                metadata:
                  name: gitops-cluster-placement
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - global
                  predicates:
                    - requiredClusterSelector:
                        labelSelector:
                          matchLabels:
                            vendor: OpenShift
                            cloud: Amazon
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-cluster
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps.open-cluster-management.io/v1beta1
                kind: GitOpsCluster
                metadata:
                  name: gitops-cluster
                  namespace: openshift-gitops
                spec:
                  argoServer:
                    cluster: local-cluster
                    argoNamespace: openshift-gitops
                  placementRef:
                    kind: Placement
                    apiVersion: cluster.open-cluster-management.io/v1beta1
                    name: gitops-cluster-placement
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: gitops-integration-policy-binding
  namespace: open-cluster-management-policies
placementRef:
  name: gitops-integration-policy-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: gitops-integration-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: gitops-integration-policy-placement
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      name: local-cluster