apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: ocp-01-cdoan-01
  namespace: us-west-2
spec:
  type: ocp
  region: us-west-2
  domain: rosa.mturansk-test.csu2.i3.devshift.org
  
  # Minimal compute config
  compute:
    instanceType: m6i.2xlarge
    replicas: 2
    
  # Type-specific configuration
  openshift:
    version: "4.15"
    channel: stable
