apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: openshift-gitops
data:
  admin.enabled: "true"
  application.instanceLabelKey: app.kubernetes.io/instance
  application.resourceTrackingMethod: label
  configManagementPlugins: ""
  dex.config: |
    connectors:
    - config:
        clientID: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-dex-server
        clientSecret: $oidc.dex.clientSecret
        groups: []
        insecureCA: true
        issuer: https://kubernetes.default.svc
        redirectURI: https://openshift-gitops-server-openshift-gitops.apps.mturansk3.rosa.mturansk-test.csu2.i3.devshift.org/api/dex/callback
      id: openshift
      name: OpenShift
      type: openshift
  ga.anonymizeusers: "false"
  ga.trackingid: ""
  help.chatText: ""
  help.chatUrl: ""
  kustomize.buildOptions: ""
  oidc.config: ""
  repositories: ""
  repository.credentials: ""
  resource.exclusions: "ffff"
  resource.inclusions: ""
  statusbadge.enabled: "false"
  url: "https://openshift-gitops-server-openshift-gitops.apps.mturansk3.rosa.mturansk-test.csu2.i3.devshift.org"
  users.anonymous.enabled: "false"