---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  namespace: ocp-01
  name: ocp-01
spec:
  baseDomain: bootstrap.red-chesterfield.com
  clusterName: ocp-01
  controlPlaneConfig:
    servingCertificates: {}
  platform:
    aws:
      credentialsSecretRef:
        name: aws-credentials
      region: us-east-1
  provisioning:
    imageSetRef:
      name: img4.19.0-multi-appsub
    installConfigSecretRef:
      name: install-config
  pullSecretRef:
    name: pull-secret
  