apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ocp-01
  labels:
    name: ocp-01
    cloud: Amazon
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: default
spec:
  hubAcceptsClient: true
