---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: High
  enableClusterBackup: false
  overrides:
    components:
    - name: cluster-manager
      enabled: true
    - name: discovery
      enabled: true
    - name: hive
      enabled: true
    - name: assisted-service
      enabled: true
    - name: server-foundation
      enabled: true
    - name: management-ingress
      enabled: true
    - name: console
      enabled: true
    - name: insights
      enabled: true
    - name: grc
      enabled: true
    - name: search
      enabled: true
    - name: cluster-lifecycle
      enabled: true
    - name: volsync
      enabled: true
    - name: multicluster-observability
      enabled: true
    - name: cluster-proxy-addon
      enabled: true
    - name: hypershift
      enabled: true
  infrastructureCustomizations:
    infrastructureProviders:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: openstack
      enabled: true
    - name: baremetal
      enabled: true
