apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cloud-infrastructure-provisioning-run
  annotations:
    description: "Pipeline run for cluster-10 (OCP) infrastructure provisioning"
spec:
  pipelineRef:
    name: cloud-infrastructure-provisioning-pipeline
  params:
    - name: cluster-name
      value: "cluster-10"
    - name: cloud-provider
      value: "aws"
    - name: region
      value: "us-east-1"
    - name: instance-type
      value: "t3a.xlarge"
    - name: node-count
      value: "1"
    - name: dry-run
      value: "false"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "2h0m0s"
    tasks: "30m0s"
    finally: "10m0s"