# This manifest creates a new ServiceAccount named 'argo-cluster-importer'
# in the 'openshift-gitops' namespace. This ServiceAccount will be used
# by a Pod or Job that needs to create Secrets.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-cluster-importer
  namespace: openshift-gitops
---
# This manifest creates a ClusterRole named 'secret-pod-manager-clusterrole'.
# A ClusterRole is a non-namespaced resource. This role grants permissions
# to read (get, list, watch) and create both 'secrets' and 'pods'.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-importer-clusterrole
rules:
  - apiGroups: ["*"] # The empty "" apiGroup refers to the core Kubernetes API group.
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "patch"]
---
# This manifest creates a ClusterRoleBinding named 'bind-cluster-resource-manager'.
# It binds the 'secret-pod-manager-clusterrole' to the 'cluster-resource-manager-sa' ServiceAccount.
# This grants the ServiceAccount the permissions defined in the ClusterRole across all namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-argo-cluster-importer
subjects:
  - kind: ServiceAccount
    name: argo-cluster-importer
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argo-cluster-importer-clusterrole
  apiGroup: rbac.authorization.k8s.io