---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: cluster-42-worker
  namespace: cluster-42
spec:
  instanceType: m5.xlarge
  scaling:
    minSize: 2
    maxSize: 20
    desiredSize: 5
  diskSize: 30
  amiType: AL2_x86_64
  capacityType: ON_DEMAND
  labels:
    cluster.x-k8s.io/cluster-name: cluster-42
  roleArn: ""
  # Will be populated by CAPI
  providerIDList: []