apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster-40
  namespace: cluster-40
  labels:
    name: cluster-40
    cloud: Amazon
    region: ap-southeast-1
    vendor: EKS
spec:
  hubAcceptsClient: true
