apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-01-mturansk-a
  namespace: eks-01-mturansk-a
  labels:
    cloud: Amazon
    region: ap-southeast-1
    vendor: EKS
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: eks-01-mturansk-a
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    name: eks-01-mturansk-a
