apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- deployment.yaml
- configmap.yaml
- servicemonitor.yaml

# Add labels for GitOps tracking
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: cluster-provisioning-metrics
    app.kubernetes.io/component: metrics-exporter
    app.kubernetes.io/part-of: openshift-bootstrap
    app.kubernetes.io/managed-by: argocd