apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- deployment.yaml
- servicemonitor.yaml

configMapGenerator:
- name: cluster-provisioning-metrics-script
  files:
  - metrics_exporter.py
  - requirements.txt

# Add labels for GitOps tracking
commonLabels:
  app.kubernetes.io/name: cluster-provisioning-metrics
  app.kubernetes.io/component: metrics-exporter
  app.kubernetes.io/part-of: openshift-bootstrap
  app.kubernetes.io/managed-by: argocd