apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cloud-infrastructure-provisioning-run
  annotations:
    description: "Example PipelineRun for cloud infrastructure provisioning"
spec:
  pipelineRef:
    name: cloud-infrastructure-provisioning-pipeline
  params:
    - name: cluster-name
      value: "demo-cluster-50"
    - name: cloud-provider
      value: "aws"
    - name: region
      value: "us-west-2"
    - name: instance-type
      value: "m5.xlarge"
    - name: node-count
      value: "5"
    - name: dry-run
      value: "true"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "2h0m0s"
    tasks: "30m0s"
    finally: "10m0s"