apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  version: "v0.0.1"

resources:
  - ../../operators/openshift-pipelines/operator/overlays/pipelines-operator-only
  - cloud-infrastructure-provisioning.pipeline.yaml

