apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-eks-01-mturansk-a

commonAnnotations:
  cluster: eks-01-mturansk-a
  cluster-type: eks
  version: "v0.0.1"

resources:
  - cloud-infrastructure-provisioning.pipelinerun.yaml

components:
  - ../../../bases/pipelines/cloud-infrastructure-provisioning
