apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster-43
  namespace: cluster-43
  labels:
    name: cluster-43
    cloud: Amazon
    region: us-west-2
    vendor: EKS
spec:
  hubAcceptsClient: true
