---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: cluster-41
  namespace: cluster-41
spec:
  region: us-west-2
  sshKeyName: ""
  version: v1.28
  baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
  vpc:
    availabilityZoneUsageLimit: 2
    availabilityZoneSelection: Ordered
  logging:
    enable: false
  associateOIDCProvider: true
  eksClusterName: cluster-41