apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  version: "v0.0.1"

resources:
  - namespace.yaml
  - cluster.yaml
  - awsmanagedcontrolplane.yaml
  - awsmanagedmachinepool.yaml
  - managedcluster.yaml
  - klusterletaddonconfig.yaml