apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster-41
  labels:
    vendor: EKS
    cloud: Amazon
    region: us-west-2
    cluster.open-cluster-management.io/clusterset: global
spec:
  hubAcceptsClient: true