apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - awsmanagedcontrolplane.yaml
  - awsmanagedmachinepool.yaml
  - managedcluster.yaml
  - klusterletaddonconfig.yaml
  - external-secrets.yaml

generatorOptions:
  disableNameSuffixHash: true
