apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hive-managed-clusters

resources:
  - namespace.yaml
  - openshift.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cluster-01-install-config
    files:
      - install-config.yaml
