apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-20
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/openshift-online/bootstrap'
    path: clusters/cluster-20
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
