apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regional-deployments-cluster-10
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: https://api.cluster-10.rosa.mturansk-test.csu2.i3.devshift.org:6443
  project: default
  source:
    repoURL: 'https://github.com/openshift-online/bootstrap'
    path: regional-deployments/overlays/cluster-10
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
