apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitea-test-applications
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Delete=false
spec:
  generators:
  - list:
      elements:
      - component: cluster
        path: clusters/eks-05-gitea-final
        destination: https://kubernetes.default.svc
        syncWave: "1"
  template:
    metadata:
      name: gitea-test-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: http://gitea.gitea-system.svc.cluster.local:3000/bootstrap/bootstrap.git
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: false
        prune: false