kind: Kustomization

resources:
- ./advanced-cluster-management.application.yaml
- ./ocm.application.yaml
- ./openshift-pipelines-operator.application.yaml
- ./cluster-01.ocm.application.yaml
- ./cluster-02.ocm.application.yaml
- ./cluster-03.ocm.application.yaml