kind: Kustomization

namespace: openshift-gitops

resources:
# Global applications (base cluster infrastructure)
- ./global/

# ADD CLUSTERS HERE

- ./eks-01-mturansk-jul30.yaml

- ./ocp-01-mturansk-jul29.yaml






















