apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
# Global applications (base cluster infrastructure)
- ./global/

# Edit the repoURL and targetRevision values below to customize for your environment
patches:
- target:
    kind: Application
    name: advanced-cluster-management
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme
      
- target:
    kind: Application
    name: openshift-pipelines-operator
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: acm-gitops-integration
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: cluster-provisioning-metrics
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: vault
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: eso
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: gitea
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme

- target:
    kind: Application
    name: cluster-bootstrap
    group: argoproj.io
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/markturansky/acme/
    - op: replace
      path: /spec/source/targetRevision
      value: OCM-16599/acme