kind: Kustomization

namespace: openshift-gitops

resources:
- ./namespace.yaml
- ./advanced-cluster-management.application.yaml
- ./openshift-pipelines-operator.application.yaml
- ./vault.application.yaml
- ./eso.application.yaml
- ./regional-clusters.cluster-10.application.yaml
- ./regional-deployments.cluster-10.application.yaml
- ./acm-gitops-integration.application.yaml
#- ./regional-pipelines.cluster-10.application.yaml

