kind: Kustomization

namespace: openshift-gitops

resources:
- ./global/namespace.yaml
- ./global/advanced-cluster-management.application.yaml
- ./global/openshift-pipelines-operator.application.yaml
- ./global/acm-gitops-integration.application.yaml #imports new managed clusters into argo

- ./global/vault.application.yaml
- ./global/eso.application.yaml

#- ./cluster-50.yaml
#- ./cluster-10.yaml
#- ./cluster-20.yaml
#- ./cluster-30.yaml
