apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocm-in-a-box
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: 'https://github.com/markturansky/managed-openshift-in-a-box-gitops'
    path: applications/ocm
    targetRevision: add_cs_app
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
