apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regional-pipelines-config
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: 'https://github.com/openshift-online/bootstrap'
    path: pipelines-config
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
