apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regional-cluster-20
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: clusters/overlay/cluster-20
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
