apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regional-cluster-41
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: clusters/overlay/cluster-41
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Prune=false