apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regional-pipelines-cluster-30
  namespace: openshift-gitops
spec:
  destination:
    name: cluster-30
    server: https://api.cluster-30.rosa.mturansk-test.csu2.i3.devshift.org:6443
  project: default
  source:
    repoURL: 'https://github.com/openshift-online/bootstrap'
    path: pipelines
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
