apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: vault
  project: default
  source:
    path: ''
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    chart: vault
    helm:
      parameters:
        - name: global.openshift
          value: "true"
        - name: server.dev.enabled
          value: "true"
  sources: []
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
