apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea-system
data:
  app.ini: |
    [server]
    PROTOCOL = http
    DOMAIN = gitea-gitea-system.apps.cluster.local
    ROOT_URL = http://gitea-gitea-system.apps.cluster.local/
    HTTP_PORT = 3000
    DISABLE_SSH = false
    SSH_PORT = 22
    OFFLINE_MODE = true
    
    [database]
    DB_TYPE = sqlite3
    PATH = /tmp/gitea/gitea.db
    
    [repository]
    ROOT = /tmp/gitea/repositories
    DISABLE_HTTP_GIT = false
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = bootstrap-gitea-secret-key-change-in-production
    INTERNAL_TOKEN = bootstrap-internal-token-change-in-production
    
    [service]
    DISABLE_REGISTRATION = true
    REQUIRE_SIGNIN_VIEW = false
    
    [admin]
    DISABLE_REGULAR_ORG_CREATION = true
    
    [log]
    MODE = console
    LEVEL = Info