apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea-system
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      serviceAccountName: gitea-init
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: generate-secrets
        image: registry.redhat.io/openshift4/ose-cli
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "🔐 Generating Gitea security secrets..."
          
          # Generate random secrets
          SECRET_KEY=$(openssl rand -hex 32)
          INTERNAL_TOKEN=$(openssl rand -base64 32)
          ADMIN_PASSWORD=$(openssl rand -base64 32)
          
          # Create temporary app.ini with generated secrets
          cp /etc/gitea/app.ini /tmp/secrets/app.ini
          
          # Replace placeholder values with generated secrets
          sed -i "s/SECRET_KEY = \$(openssl rand -hex 32)/SECRET_KEY = ${SECRET_KEY}/g" /tmp/secrets/app.ini
          sed -i "s/INTERNAL_TOKEN = \$(openssl rand -base64 32)/INTERNAL_TOKEN = ${INTERNAL_TOKEN}/g" /tmp/secrets/app.ini
          
          # Update admin password secret
          oc patch secret gitea-admin-secret -n gitea-system --type='merge' -p="{\"data\":{\"password\":\"$(echo -n $ADMIN_PASSWORD | base64)\"}}"
          
          echo "✅ Generated unique security secrets for Gitea"
        volumeMounts:
        - name: gitea-app-ini
          mountPath: /etc/gitea
          readOnly: true
        - name: gitea-secrets
          mountPath: /tmp/secrets
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: gitea
        image: quay.io/gpte-devops-automation/gitea:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: gitea-data
          mountPath: /tmp/gitea
        - name: gitea-secrets
          mountPath: /home/gitea/conf
          readOnly: true
        env:
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "gitea-db.gitea-system.svc.cluster.local:5432"
        - name: GITEA__database__NAME
          value: "gitea"
        - name: GITEA__database__USER
          value: "gitea"
        - name: GITEA__database__PASSWD
          value: "giteapassword123"
        - name: GITEA__repository__ROOT
          value: "/tmp/gitea/repositories"
        - name: GITEA_WORK_DIR
          value: "/tmp/gitea"
        - name: GITEA_CUSTOM
          value: "/tmp/gitea"
        - name: GITEA_ADMIN_USERNAME
          value: "gitea-admin"
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-admin-secret
              key: password
        - name: GITEA_ADMIN_EMAIL
          value: "admin@example.com"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data
      - name: gitea-app-ini
        configMap:
          name: gitea-app-ini
      - name: gitea-secrets
        emptyDir: {}
