apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-init
  namespace: gitea-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-init
  namespace: gitea-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-init
  namespace: gitea-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-init
subjects:
- kind: ServiceAccount
  name: gitea-init
  namespace: gitea-system