apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-repo-setup-v4
  namespace: gitea-system
  annotations: {}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: gitea-repo-setup
      containers:
      - name: setup
        image: registry.redhat.io/openshift4/ose-cli
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "🏗️ Setting up Gitea bootstrap repository..."
          
          # ose-cli already has git, just verify
          git --version
          
          # Simple git-based setup - clone and push
          echo "📥 Cloning GitHub repository..."
          
          # Create temporary directory for git operations
          mkdir -p /tmp/git-work
          cd /tmp/git-work
          
          # Clone the GitHub repository
          git clone https://github.com/openshift-online/bootstrap.git github-bootstrap
          cd github-bootstrap
          
          # Configure git for the push
          git config user.name "Gitea Repository Setup"
          git config user.email "gitea-setup@cluster.local"
          
          # Add Gitea remote with credentials (assuming admin user exists)
          git remote add gitea http://myadmin:mysecurepassword@gitea.gitea-system.svc.cluster.local:3000/myadmin/bootstrap.git
          
          echo "📤 Pushing repository content to Gitea..."
          echo "📋 Repository contents:"
          ls -la
          echo "📁 Bin directory contents:"
          ls -la bin/
          
          # Push all content to Gitea (will create repo if it doesn't exist)
          git push gitea main --force
          
          echo "✅ Successfully pushed bootstrap repository content to Gitea using git"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-repo-setup
  namespace: gitea-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-repo-setup
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "pods/exec"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-repo-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-repo-setup
subjects:
- kind: ServiceAccount
  name: gitea-repo-setup
  namespace: gitea-system