apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - app-ini-configmap.yaml
  - pvc.yaml
  - route.yaml
  - argocd-gitea-secret.yaml