apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cloud-infrastructure-provisioning-run
  namespace: ocm-ocp-03
spec:
  pipelineRef:
    name: cloud-infrastructure-provisioning
  params:
    - name: cluster-name
      value: ocp-03
    - name: region
      value: us-east-1
