---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/enable-console-plugin
  - ../../components/pipeline-rbac

patches:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: openshift-pipelines-operator
      namespace: openshift-operators
      version: v1alpha1
