apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-hcp-01-mturansk-test

commonAnnotations:
  cluster: hcp-01-mturansk-test
  cluster-type: hcp
  version: "v0.0.1"

resources:
  - hello-world.pipelinerun.yaml

components:
  - ../../../bases/pipelines/hello-world
