apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-hcp-02-mturansk-test

commonAnnotations:
  cluster: hcp-02-mturansk-test
  cluster-type: hcp
  version: "v0.0.1"

resources:
  - ../global/overlays/pipelines-operator-only
  - namespace.yaml
