apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-operators

resources:
  - console-plugin-job.yaml
  - console-plugin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-tekton-console-plugin-scripts
    namespace: openshift-operators
    files:
      - console-plugin-job.sh
