apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: eks-40
  namespace: ap-southeast-1
spec:
  type: eks
  region: ap-southeast-1
  domain: rosa.mturansk-test.csu2.i3.devshift.org
  compute:
    instanceType: m5.large
    replicas: 1
