apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: hello-world-run
  namespace: ocm-eks-test-20250720-001500
spec:
  pipelineRef:
    name: hello-world-pipeline
  params:
    - name: cluster-name
      value: eks-test-20250720-001500
    - name: region
      value: us-west-2
