apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: hcp-02-mturansk-test
  namespace: hcp-02-mturansk-test
  annotations:
    hypershift.openshift.io/pod-security-admission-label-override: privileged
spec:
  release:
    image: "quay.io/openshift-release-dev/ocp-release@sha256:45a396b169974dcbd8aae481c647bf55bcf9f0f8f6222483d407d7cec450928d"
  pullSecret:
    name: pull-secret
  sshKey:
    name: "hcp-02-mturansk-test-ssh-key"
  infrastructureAvailabilityPolicy: SingleReplica
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  platform:
    type: AWS
    aws:
      region: us-east-1
      credentialsSecretRef:
        name: aws-credentials-test
      rolesRef:
        kubeCloudControllerARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        nodePoolManagementARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        controlPlaneOperatorARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        networkARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        storageARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        imageRegistryARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
        ingressARN: arn:aws:iam::765374464689:role/controllers.cluster-api-provider-aws.sigs.k8s.io
  infraID: hcp-02-mturansk-test
  dns:
    baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: None
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
