apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-eks-01-mturansk-test

commonAnnotations:
  cluster: eks-01-mturansk-test
  cluster-type: eks
  version: "v0.0.1"

resources:
  - hello-world.pipelinerun.yaml

components:
  - ../../../bases/pipelines/hello-world
