apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-cluster-30

commonAnnotations:
  cluster: cluster-30
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - ../../../operators/openshift-pipelines/operator/overlays/pipelines-operator-only
  - cloud-infrastructure-provisioning.pipelinerun.yaml

components:
  - ../../../bases/pipelines/cloud-infrastructure-provisioning
