apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: ocp-01-acme6
  namespace: us-west-2
spec:
  type: ocp
  region: us-west-2
  domain: 15c7.i1.devshift.org
  
  # Minimal compute config
  compute:
    instanceType: m5.2xlarge
    replicas: 2
    
  # Type-specific configuration
  openshift:
    version: "4.15"
    channel: stable
