apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: hcp-01-mturansk-test
  namespace: hcp-01-mturansk-test
  annotations:
    hypershift.openshift.io/pod-security-admission-label-override: privileged
spec:
  release:
    image: "quay.io/openshift-release-dev/ocp-release@sha256:45a396b169974dcbd8aae481c647bf55bcf9f0f8f6222483d407d7cec450928d"
  pullSecret:
    name: pull-secret
  sshKey:
    name: "hcp-01-mturansk-test-ssh-key"
  infrastructureAvailabilityPolicy: SingleReplica
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  platform:
    type: None
  infraID: hcp-01-mturansk-test
  dns:
    baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: NodePort
      nodePort:
        address: api.hcp-01-mturansk-test.rosa.mturansk-test.csu2.i3.devshift.org
  - service: OIDC
    servicePublishingStrategy:
      type: None
  - service: Konnectivity
    servicePublishingStrategy:
      type: LoadBalancer
  - service: Ignition
    servicePublishingStrategy:
      type: NodePort
      nodePort:
        address: api.hcp-01-mturansk-test.rosa.mturansk-test.csu2.i3.devshift.org
