apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  version: "v0.0.1"

resources:
  - ams.db.yaml
  - cs.db.yaml
  - osl.db.yaml

secretGenerator:
  - name: ams-db
    literals:
      - db.host="ams-db"
      - db.name="ams-db"
      - db.password="foobar"
      - db.user="ams-db"
      - db.port="5432"
  - name: cs-db
    literals:
      - db.host="cs-db"
      - db.name="cs-db"
      - db.password="foobar"
      - db.user="cs-db"
      - db.port="5432"
  - name: osl-db
    literals:
      - db.host="osl-db"
      - db.name="osl-db"
      - db.password="foobar"
      - db.user="osl-db"
      - db.port="5432"
