---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication
data:
  # The OCM services read the JSON web keys used to verify authentication
  # tokens from the URL of the SSO service:
  #
  #   https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs
  #
  # The content of this file has been extracted from that URL and is used as a
  # backup in case the connection to that URL fails.
  jwks.json: |-
    {
      "keys": [
        {
          "kid": "-4elc_VdN_WsOUYf2G4Qxr8GcwIx_KtXUCitatLKlLw",
          "kty": "RSA",
          "alg": "RS256",
          "use": "sig",
          "n": "5MvhbE1Mxr2FUYGZiH0z6p-kV-FIUHp4ErxkD6S8Sc5OB7IjRKDSsJzmuwR803cKpeKoIkkUTiznYwCBqAUdP3bIZ8k97X6GX19dOSqL4ej1rjYZYAf9_Jt_Z-0PzIjX50z6TpqeGoh7-6P-634SvbdjatnhTAQ3qsBXfPOHPIPRAZkGfmlM1EdvIlm_d2hQ7nDSETbVC4YHY-iESvUhre-aNmqJU_E6fRnGwFTPS20fPLE5bUNbshvTXn5c-bxtWK9bSCHCRVYUF9QWwDoFX9gGOIpSScHAKQLRR16yOQjOioZ2FeVZnDpWNvZelbQ7LtLN0H5uCJsqDoZDDhDWeFp-25O9ih5M9auT_2IepUlOq3OBMj7i3CJXrvjNQiuGkPHp9xN6kd5H4E5hcqUTmfYdgf1IuXP0cTwYtQor21dWBSpFvxW8l1HGLOaO_rSetNRJ-tZ7FKUK5L6crt1N72AGIay96gNOWNe4POOG_ML1r4h3SKBFdMPwJ-R5KDg7-oRcUT4kLuFtWuQG7bKLJhIxw_SnVFajLGt1d3-OCqX6ozuUbdEW31f9iLZd4w-NUSSHjxP1Uvalk5QfUro9w9fTW73jRIUASnbHunopjt_IkiQswrdIwpfpeBokcf9O757_i0kctQ5M1gyPf4-0yPfuDVkeBAHygoxNJU9H3C0",
          "e": "AQAB"
        }
      ]
    }

  # This access control list is used only in the integration and staging
  # environments to make sure that only users with a `redhat.com` e-mail
  # address can access. In the production environment it must be empty.
  acl.yml: |-
    - claim: email
      pattern: ^.*@redhat\.com$