---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  namespace: regional-clusters
  name: cluster-01
spec:
  baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
  clusterName: cluster-01
  controlPlaneConfig:
    servingCertificates: {}
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds
      region: us-east-1
  provisioning:
    imageSetRef:
      name: img4.19.0-multi-appsub
    installConfigSecretRef:
      name: install-config
  pullSecretRef:
    name: pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster-01
  labels:
    cloud: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    name: cluster-01
    vendor: auto-detect
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: cluster-01-worker
  namespace: cluster-01
spec:
  clusterDeploymentRef:
    name: 'cluster-01'
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: t3a.xlarge  # 4 vCPU, 16 GiB RAM - General Purpose
      zones:
        - us-east-1c
  replicas: 1
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster-01
  namespace: cluster-01
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    name: cluster-01
    vendor: auto-detect
  clusterName: cluster-01
  clusterNamespace: cluster-01
  policyController:
    enabled: true
  searchCollector:
    enabled: true
