apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: regional-clusters

resources:
  - namespace.yaml
  - cluster.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: install-config
    files:
      - install-config.yaml
