apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster-01
  labels:
    cloud: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    name: cluster-01
    vendor: auto-detect
spec:
  hubAcceptsClient: true
