apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cluster: eks-02
  cluster-type: eks
  version: "v0.0.1"

resources:
  - ../global/overlays/pipelines-operator-only