apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cloud-infrastructure-provisioning-run
  namespace: ocm-eks-05-gitea-final
spec:
  pipelineRef:
    name: cloud-infrastructure-provisioning-pipeline
  params:
    - name: cluster-name
      value: eks-05-gitea-final
    - name: cloud-provider
      value: aws
    - name: region
      value: us-east-2
    - name: instance-type
      value: m5.large
    - name: node-count
      value: "2"
