apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster-01
  namespace: cluster-01
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: Amazon
    name: cluster-01
    vendor: OpenShift
  clusterName: cluster-01
  clusterNamespace: cluster-01
  policyController:
    enabled: true
  searchCollector:
    enabled: true
