apiVersion: v1
metadata:
  name: 'ocp-05'
baseDomain: rosa.mturansk-test.csu2.i3.devshift.org
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      zones:
        - eu-west-1a
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.large
compute:
  - hyperthreading: Enabled
    architecture: amd64
    name: 'worker'
    replicas: 2
    platform:
      aws:
        rootVolume:
          iops: 2000
          size: 100
          type: io1
        type: m5.large
        zones:
          - eu-west-1a
networking:
  networkType: OVNKubernetes
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.0.0.0/16
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-1
pullSecret: "" # skip, hive will inject based on it's secrets
