apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: hello-world-run
  namespace: ocm-cluster-40
spec:
  pipelineRef:
    name: hello-world-pipeline
  params:
    - name: cluster-name
      value: cluster-40
    - name: region
      value: ap-southeast-1
