---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: cluster-40-worker
  namespace: cluster-40
spec:
  instanceType: m5.large
  scaling:
    minSize: 1
    maxSize: 10
    desiredSize: 3
  diskSize: 30
  amiType: AL2_x86_64
  capacityType: ON_DEMAND
  labels:
    cluster.x-k8s.io/cluster-name: cluster-40
  roleArn: ""
  # Will be populated by CAPI
  providerIDList: []