---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: cluster-40
  namespace: cluster-40
spec:
  region: ap-southeast-1
  sshKeyName: ""
  version: v1.28
  vpc:
    availabilityZoneUsageLimit: 2
    availabilityZoneSelection: Ordered
  logging:
    enable: false
  associateOIDCProvider: true
  eksClusterName: cluster-40