apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - awsmanagedcontrolplane.yaml
  - awsmanagedmachinepool.yaml
  - machinepool.yaml
  - managedcluster.yaml
  - klusterletaddonconfig.yaml

# This will disable name hashing for all generators in this file
generatorOptions:
  disableNameSuffixHash: true