apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-management
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/advanced-cluster-management/global
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - SkipDryRunOnMissingResource=true
    prune: false
    retry: # Extending the backoff / retry because ACM has to install before all CRs can finalize
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m