apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: eks-test-20250719-194218
  namespace: us-west-2
spec:
  type: eks
  region: us-west-2
  domain: rosa.mturansk-test.csu2.i3.devshift.org
  
  compute:
    instanceType: m5.large
    replicas: 3
    
  kubernetes:
    version: "1.28"