apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: ocp-01-mturansk-test
  namespace: us-east-2
spec:
  type: ocp
  region: us-east-2
  domain: rosa.mturansk-test.csu2.i3.devshift.org
  
  # Minimal compute config
  compute:
    instanceType: m5.large
    replicas: 3
    
  # Type-specific configuration
  openshift:
    version: "4.15"
    channel: stable
