apiVersion: regional.openshift.io/v1
kind: RegionalCluster
metadata:
  name: eks-01-mturansk-a
  namespace: ap-southeast-1
spec:
  type: eks
  region: ap-southeast-1
  domain: rosa.mturansk-test.csu2.i3.devshift.org
  
  # Minimal compute config
  compute:
    instanceType: m5.2xlarge
    replicas: 2
    
  # Type-specific configuration
  kubernetes:
    version: "1.28"
