apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-gitops-integration
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/gitops-integration/global
    repoURL: 'https://github.com/openshift-online/bootstrap'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: true