kind: Kustomization

namespace: openshift-gitops

resources:
- ./advanced-cluster-management-set.application.yaml
- ./openshift-pipelines-operator.application.yaml
- ./acm-gitops-integration.application.yaml #imports new managed clusters into argo
- ./cluster-provisioning-metrics.application.yaml # monitors cluster provisioning
- ./vault.application.yaml
- ./eso.application.yaml
- ./gitea.application.yaml

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: advanced-cluster-management
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: openshift-pipelines-operator
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: acm-gitops-integration
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: cluster-provisioning-metrics
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: vault
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    name: gitea
  patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: "https://github.com/markturansky/acme"