---
# AWS credentials for CAPI EKS cluster provisioning
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: ${CLUSTER_NAME}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: aws-credentials
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: aws-credentials
      property: aws_secret_access_key
---
# Pull secret for container registry access
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: ${CLUSTER_NAME}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: pull-secret
    creationPolicy: Owner
    type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: pull-secret
      property: .dockerconfigjson