apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: CLUSTER_NAME
  namespace: CLUSTER_NAME
spec:
  clusterName: CLUSTER_NAME
  replicas: REPLICAS
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: CLUSTER_NAME
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: CLUSTER_NAME
      version: KUBERNETES_VERSION