# EKS Workers Template - AWSManagedMachinePool
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: ${CLUSTER_NAME}-worker
  namespace: ${CLUSTER_NAME}
spec:
  instanceType: ${INSTANCE_TYPE}
  scaling:
    minSize: ${MIN_NODES}
    maxSize: ${MAX_NODES}
    desiredSize: ${DESIRED_NODES}
  diskSize: 30
  amiType: AL2_x86_64
  capacityType: ON_DEMAND
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  roleArn: ""
  # Will be populated by CAPI
  providerIDList: []