apiVersion: v1
kind: Secret
metadata:
  name: hashicorp-helm-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: hashicorp
  url: https://helm.releases.hashicorp.com