apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-secret-reader
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-secret-reader
subjects:
- kind: ServiceAccount
  name: vault-secret-reader
  namespace: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret-reader-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: vault-secret-reader
type: kubernetes.io/service-account-token