apiVersion: v1
kind: Secret
metadata:
  name: cluster-10-secret
  namespace: openshift-gitops
  labels:
    # This label is required for Argo CD to recognize this as a cluster secret
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  # The name of the cluster. This will be displayed in the Argo CD UI.
  name: cluster-10
  # The API server URL of the destination cluster.
  server: "https://api.cluster-10.rosa.mturansk-test.csu2.i3.devshift.org:6443"
  server.insecure: "true"
  # The configuration for connecting to the cluster.
  config: |
    {
      "bearerToken": "sha256~cS5jtmDoj-AgyMH_I31kq7OjFG_xzQMNNbLykInS9Zc",
      "tlsClientConfig": {
        "insecure": "true",
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lJQU9oQkl1elB2THd3RFFZSktvWklodmNOQVFFTEJRQXdLekVwTUNjR0ExVUUKQXd3Z1lYSm5iMk5rTFc5d1pYSmhkRzl5UUc5d1pXNXphR2xtZEMxbmFYUnZjSE13SGhjTk1qVXdOekEzTVRVeApNVE16V2hjTk1qWXdOekEzTVRVeE1UTXpXakFyTVNrd0p3WURWUVFERENCaGNtZHZZMlF0YjNCbGNtRjBiM0pBCmIzQmxibk5vYVdaMExXZHBkRzl3Y3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUxXUEtaaXIxb05WTWswbXVRMUdNWEc5MkhEeTVzaHl5djRuTUxQZ1Z6aWVhMkc0ektxcUE4bGVEMXFidGRwUQpKcTYwUnZaTjlOdEhBbjlGYzFwNDhsZ3VZVTR1QzAvREpRUW1oQzAwelo4d2YycXZ0NnJETlYzUTRVdG1jL0tOCkRLRFdta3Bza05BSEZ3RGdZNlpCQ2ZFaUY1ZExnU3hveWNNd2hCWkRIQTljV1V6REtnTVduTVpIcllGSFg4S2YKZmlQeUpFa2ZLUXIrMWxqOWVDamVrSGlWcVJJMU1LcHVCalJoVXk4dDR2TmFkR3E1MC9GQytWWTVRUnQ3eWZRWQpNcGYxVmRqemF1dlQ3NnZPWnREcjk4a0dseGZvUW5IOXY1dklBS2xpTXh1THBleWV3RlFEMUhyRTEyZEdrYXdkCkdveUx4TmFYcUE5TmhDU1orb01xdW1rQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKdlhLOFRjUE1mOVRkcjZYWUprRFRzTWZQUXJNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFBa1k1YVVaVGgrM29tRllXTXJuRHlwcTMrbnd1V3BvZVd3NjdPbnlSWWR6L3N3Ckl3K1RqakM5bWI4aFluTVYwVllCd3krWE9saWNrUWxQdkFSei9yWlNxbEh5RTV3ZGczdWF4SnRRT0FlMm9MQmIKMEVsMzVNNXNlVUpWVGV1OWk4bnAzS1N4dUszQlFYMnBzcUZ5SUNMcXdUVGkzLzlQK1BuZ3U3UWZoUW9maU9NegpONG5uNmtnQWVxZ1Q5eGlYVU1VV3RrL1NHRlUrblFxMzFVUEQwZ1Q4N1FadTVPdWtRS1BENG5Wa0lsckRYV0lLClJ4a2ZlQm44V2tZT3dmcHV3Ylo4aWN6YTFzUlNFUXZ0WmpqQUpXSGV4YXYzVDl5VWtvaFpKUkUzcjZralB4QTAKNE84eWJtckVyWGhkMzA2MFYvY3VMdjZwNEpZdHRSU1AxaElkbGFmbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      }
    }